---
- name: Run my roles
  hosts: Cloud1
  become: yes
  roles:
    - install_python
    - install_docker
    - install_make
    - install_nginx
    - deploy_ssl
    - setup_app
    - run_app
    #- run_database
    #- run_phpmyadmin
    #- word_press
    #- clean_app
    #- uninstall_docker
    #- restart_conatiner
