Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant"

  # Server Machine
  config.vm.define "abel-bouS" do |server|
    server.vm.hostname = "abel-bouS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider"virtualbox" do |vb|
      vb.name = "abel-bouS"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end