- name: Ensure data directories exist for Docker volumes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /home/{{ ansible_user }}/data/mariadb
    - /home/{{ ansible_user }}/data/wordpress

- name: Create app directory
  file:
    path: "/home/{{ ansible_user }}/Desktop/app"
    state: directory
    mode: '0755'

- name: Copy Makefile to app directory
  copy:
    src: files/wordpress_role/Makefile
    dest: /home/{{ ansible_user }}/Desktop/app/Makefile
    mode: '0644'

- name: Create app srcs and requirements directories
  file:
    path: "/home/{{ ansible_user }}/Desktop/app/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - srcs
    - srcs/requirements

- name: Copy .env file to app directory
  copy:
    src: files/wordpress_role/srcs/docker-compose.yml
    dest: /home/{{ ansible_user }}/Desktop/app/srcs/docker-compose.yml
    mode: '0644'

- name: Copy .env file to app directory
  copy:
    src: files/wordpress_role/srcs/.env
    dest: /home/{{ ansible_user }}/Desktop/app/srcs/.env
    mode: '0644'